package com.example.logindemo.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.annotations.Field;
import org.springframework.data.elasticsearch.annotations.FieldType;

import java.util.Date;
import java.util.List;

@Document(indexName = "tb_package",type = "pack",shards = 1)
public class Packages {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.package_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Id
	@TableId(value = "package_id",type= IdType.AUTO)
	private Integer packageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.projects_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Long)
	private Integer projectsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.devc_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Long)
	private Integer devcId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.name
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Text)
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.code
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Text)
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.create_time
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Date)
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.plan_start
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Date)
	private Date planStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.plan_end
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Date)
	private Date planEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.plan_days
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Long)
	private Integer planDays;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.writer
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Long)
	private Integer writer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.exam
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Long)
	private Integer exam;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.auditor
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Long)
	private Integer auditor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.approver
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Long)
	private Integer approver;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.serv_unit_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Long)
	private Integer servUnitId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.serv_frame_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Long)
	private Integer servFrameId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.leader
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Long)
	private Integer leader;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.status
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Text)
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.repair_items
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Text)
	private String repairItems;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.target
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Text)
	private String target;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.pre_survey
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Text)
	private String preSurvey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.approval_date
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Date)
	private Date approvalDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.using_date
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Date)
	private Date usingDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.end_date
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Date)
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.has_ticket
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Boolean)
	private Boolean hasTicket;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.parent_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Long)
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.process_ins_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	@Field(type = FieldType.Long)
	private Integer processInsId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.package_id
	 * @return  the value of dbo.Packages.package_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getPackageId() {
		return packageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.package_id
	 * @param packageId  the value for dbo.Packages.package_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.projects_id
	 * @return  the value of dbo.Packages.projects_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getProjectsId() {
		return projectsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.projects_id
	 * @param projectsId  the value for dbo.Packages.projects_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setProjectsId(Integer projectsId) {
		this.projectsId = projectsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.devc_id
	 * @return  the value of dbo.Packages.devc_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getDevcId() {
		return devcId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.devc_id
	 * @param devcId  the value for dbo.Packages.devc_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setDevcId(Integer devcId) {
		this.devcId = devcId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.name
	 * @return  the value of dbo.Packages.name
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.name
	 * @param name  the value for dbo.Packages.name
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.code
	 * @return  the value of dbo.Packages.code
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.code
	 * @param code  the value for dbo.Packages.code
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.create_time
	 * @return  the value of dbo.Packages.create_time
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.create_time
	 * @param createTime  the value for dbo.Packages.create_time
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.plan_start
	 * @return  the value of dbo.Packages.plan_start
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Date getPlanStart() {
		return planStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.plan_start
	 * @param planStart  the value for dbo.Packages.plan_start
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setPlanStart(Date planStart) {
		this.planStart = planStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.plan_end
	 * @return  the value of dbo.Packages.plan_end
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Date getPlanEnd() {
		return planEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.plan_end
	 * @param planEnd  the value for dbo.Packages.plan_end
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setPlanEnd(Date planEnd) {
		this.planEnd = planEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.plan_days
	 * @return  the value of dbo.Packages.plan_days
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getPlanDays() {
		return planDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.plan_days
	 * @param planDays  the value for dbo.Packages.plan_days
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setPlanDays(Integer planDays) {
		this.planDays = planDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.writer
	 * @return  the value of dbo.Packages.writer
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getWriter() {
		return writer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.writer
	 * @param writer  the value for dbo.Packages.writer
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setWriter(Integer writer) {
		this.writer = writer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.exam
	 * @return  the value of dbo.Packages.exam
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getExam() {
		return exam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.exam
	 * @param exam  the value for dbo.Packages.exam
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setExam(Integer exam) {
		this.exam = exam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.auditor
	 * @return  the value of dbo.Packages.auditor
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getAuditor() {
		return auditor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.auditor
	 * @param auditor  the value for dbo.Packages.auditor
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setAuditor(Integer auditor) {
		this.auditor = auditor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.approver
	 * @return  the value of dbo.Packages.approver
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getApprover() {
		return approver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.approver
	 * @param approver  the value for dbo.Packages.approver
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setApprover(Integer approver) {
		this.approver = approver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.serv_unit_id
	 * @return  the value of dbo.Packages.serv_unit_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getServUnitId() {
		return servUnitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.serv_unit_id
	 * @param servUnitId  the value for dbo.Packages.serv_unit_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setServUnitId(Integer servUnitId) {
		this.servUnitId = servUnitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.serv_frame_id
	 * @return  the value of dbo.Packages.serv_frame_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getServFrameId() {
		return servFrameId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.serv_frame_id
	 * @param servFrameId  the value for dbo.Packages.serv_frame_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setServFrameId(Integer servFrameId) {
		this.servFrameId = servFrameId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.leader
	 * @return  the value of dbo.Packages.leader
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getLeader() {
		return leader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.leader
	 * @param leader  the value for dbo.Packages.leader
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setLeader(Integer leader) {
		this.leader = leader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.status
	 * @return  the value of dbo.Packages.status
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.status
	 * @param status  the value for dbo.Packages.status
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.repair_items
	 * @return  the value of dbo.Packages.repair_items
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public String getRepairItems() {
		return repairItems;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.repair_items
	 * @param repairItems  the value for dbo.Packages.repair_items
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setRepairItems(String repairItems) {
		this.repairItems = repairItems;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.target
	 * @return  the value of dbo.Packages.target
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public String getTarget() {
		return target;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.target
	 * @param target  the value for dbo.Packages.target
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setTarget(String target) {
		this.target = target;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.pre_survey
	 * @return  the value of dbo.Packages.pre_survey
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public String getPreSurvey() {
		return preSurvey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.pre_survey
	 * @param preSurvey  the value for dbo.Packages.pre_survey
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setPreSurvey(String preSurvey) {
		this.preSurvey = preSurvey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.approval_date
	 * @return  the value of dbo.Packages.approval_date
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Date getApprovalDate() {
		return approvalDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.approval_date
	 * @param approvalDate  the value for dbo.Packages.approval_date
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.using_date
	 * @return  the value of dbo.Packages.using_date
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Date getUsingDate() {
		return usingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.using_date
	 * @param usingDate  the value for dbo.Packages.using_date
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setUsingDate(Date usingDate) {
		this.usingDate = usingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.end_date
	 * @return  the value of dbo.Packages.end_date
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.end_date
	 * @param endDate  the value for dbo.Packages.end_date
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.has_ticket
	 * @return  the value of dbo.Packages.has_ticket
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Boolean getHasTicket() {
		return hasTicket;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.has_ticket
	 * @param hasTicket  the value for dbo.Packages.has_ticket
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setHasTicket(Boolean hasTicket) {
		this.hasTicket = hasTicket;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.parent_id
	 * @return  the value of dbo.Packages.parent_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.parent_id
	 * @param parentId  the value for dbo.Packages.parent_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Packages.process_ins_id
	 * @return  the value of dbo.Packages.process_ins_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public Integer getProcessInsId() {
		return processInsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Packages.process_ins_id
	 * @param processInsId  the value for dbo.Packages.process_ins_id
	 * @mbg.generated  Thu Dec 07 09:12:27 CST 2017
	 */
	public void setProcessInsId(Integer processInsId) {
		this.processInsId = processInsId;
	}


	@Field(type = FieldType.Long)
	private Integer endDays;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.fault_deal
	 * @mbg.generated  Fri Dec 22 09:55:44 CST 2017
	 */
	@Field(type = FieldType.Text)
	private String faultDeal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.unchange
	 * @mbg.generated  Fri Dec 22 09:55:44 CST 2017
	 */
	@Field(type = FieldType.Text)
	private String unchange;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.problem_mes
	 * @mbg.generated  Fri Dec 22 09:55:44 CST 2017
	 */
	@Field(type = FieldType.Text)
	private String problemMes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Packages.finish_comment
	 * @mbg.generated  Fri Dec 22 09:55:44 CST 2017
	 */
	@Field(type = FieldType.Text)
	private String finishComment;

	//交底资源相关
	@Field(type = FieldType.Text)
	private String noticeType;

	@Field(type = FieldType.Long)
	private Integer noticeTimeCount;

	@Field(type = FieldType.Long)
	private Integer noticePicCount;

	@Field(type = FieldType.Long)
	private Integer noticeVideoCount;

	//交底允许缺席人数
	@Field(type = FieldType.Long)
	private Integer presentRate;

	public Integer getPresentRate() {
		return presentRate;
	}

	public void setPresentRate(Integer presentRate) {
		this.presentRate = presentRate;
	}

	public Integer getEndDays() {
		return endDays;
	}

	public void setEndDays(Integer endDays) {
		this.endDays = endDays;
	}

	public String getFaultDeal() {
		return faultDeal;
	}

	public void setFaultDeal(String faultDeal) {
		this.faultDeal = faultDeal;
	}

	public String getUnchange() {
		return unchange;
	}

	public void setUnchange(String unchange) {
		this.unchange = unchange;
	}

	public String getProblemMes() {
		return problemMes;
	}

	public void setProblemMes(String problemMes) {
		this.problemMes = problemMes;
	}

	public String getFinishComment() {
		return finishComment;
	}

	public void setFinishComment(String finishComment) {
		this.finishComment = finishComment;
	}

	private Integer noticeNum;

	public Integer getNoticeNum() {
		return noticeNum;
	}

	public void setNoticeNum(Integer noticeNum) {
		this.noticeNum = noticeNum;
	}

	private Integer servStaffId;

	public Integer getServStaffId() {
		return servStaffId;
	}

	public void setServStaffId(Integer servStaffId) {
		this.servStaffId = servStaffId;
	}

	//添加审核人2，会审人
	@Field(type = FieldType.Long)
	private Integer exam2;
	@Field(type = FieldType.Long)
	private Integer checker;

	public Integer getExam2() {
		return exam2;
	}

	public void setExam2(Integer exam2) {
		this.exam2 = exam2;
	}

	public Integer getChecker() {
		return checker;
	}

	public void setChecker(Integer checker) {
		this.checker = checker;
	}

	public String getNoticeType() {
		return noticeType;
	}

	public void setNoticeType(String noticeType) {
		this.noticeType = noticeType;
	}

	public Integer getNoticeTimeCount() {
		return noticeTimeCount;
	}

	public void setNoticeTimeCount(Integer noticeTimeCount) {
		this.noticeTimeCount = noticeTimeCount;
	}

	public Integer getNoticePicCount() {
		return noticePicCount;
	}

	public void setNoticePicCount(Integer noticePicCount) {
		this.noticePicCount = noticePicCount;
	}

	public Integer getNoticeVideoCount() {
		return noticeVideoCount;
	}

	public void setNoticeVideoCount(Integer noticeVideoCount) {
		this.noticeVideoCount = noticeVideoCount;
	}
}
